data:
  source_url: "https://download.microsoft.com/download/3/E/1/3E1C3F21-ECDB-4869-8368-6DEBA77B919F/kagglecatsanddogs_3367a.zip"
  local_dir: data
  data_file: data.zip
  unzip_data_dir: data
  parent_data_dir: PetImages
  bad_data_folder: 'bad_data_folder'

Log_file_name: 'running_log.log'

